# Generated by Django 2.1.15 on 2020-04-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_project_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Members',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Title',
            new_name='title',
        ),
    ]
