# Generated by Django 2.1.15 on 2020-04-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20200430_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='f',
            field=models.TextField(null=True),
        ),
    ]
