# Generated by Django 2.1.15 on 2020-04-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_project_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='f',
        ),
    ]
