# Generated by Django 2.1.15 on 2020-05-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_auto_20200504_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
